### ISSUE TITLE
Documentation on PinMame Version selection

### ISSUE THREAD

**Issue by xantari** [vpinball/pinmame-dotnet#25]
A few questions:

1. Can you add Question / Issue labels and add issue/question templates in this repo (I didn't want to create an issue, wanted to create a question)
2. How are you determining which Pinmame version to latch on to? Will it be 3.2, 3.3, or 3.4 version of PinMame?

**Comment by freezy** [comment]
The vpinball/pinmame-dotnet repo updates this repo on every push, i.e. it's always the latest. And it ships with it, so it's independent of what you've installed on your system.

**Comment by xantari** [comment]
Ok, closing.

**Comment by xantari** [comment]
Sorry, one last question, how will this work with the SAMBuild version?

**Comment by freezy** [comment]
@jsm174 correct me if I'm wrong, but this is the coloring-enabled version, and SAM is part of PinMAME anyway.

**Comment by jsm174** [comment]
Currently `libpinmame` is not build with the `SAM_INCLUDE_COLORED` compiler flag. I will look into this some more.

**Comment by freezy** [comment]
Okay, not needed for now I guess until we have a colorizer working, but it shouldn't be a big deal, right?
